mybatis:
  mapper-locations: com/config/*.xml
  type-aliases-package: com.board_mybatis_thymeleaf.dto

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 123456789

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false